version: '3.3'

services:
  api-service:
    build: .
    depends_on:
      - database
    environment:
        - DATABASE_URL=postgres://admin:admin@database:5432/shortener
    ports:
        - "8080:8080"

  database:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=shortener
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: